In [2]:
import numpy as np
list=['1','2','3','4','5']
array=np.array(list)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In Python, both `list` and `array` (from the `array` module) are used to store collections of items. However, there are differences between them, including their data types and functionality.

1. **List:**
   - A `list` is a built-in Python data type that can hold items of different data types.
   - Lists are dynamic and can be resized.
   - They are more versatile and can store any data type, including mixed data types.
   - Lists are defined using square brackets `[ ]`.

2. **Array (from the `array` module):**
   - An `array` is a data structure provided by the `array` module in Python's standard library.
   - Arrays are more memory-efficient as they store items of the same data type.
   - They are less versatile compared to lists, as they can only store items of a single data type.
   - Arrays are defined using the `array.array()` constructor.

Here's a comparison of their data types:

```python
import array

list_ = [1, 2, 3, 4, 5]
array_list = array.array('i', [1, 2, 3, 4, 5])
```

In this example, `list_` is a Python list containing integers, while `array_list` is an array containing integers (`'i'` is the type code for signed integers). While they both can hold similar types of data, `array_list` is more memory-efficient due to its stricter data type constraint.

In general, if you need more flexibility and want to store different data types, you would use a Python `list`. If memory efficiency and homogeneity of data types are more important, you might consider using arrays from the `array` module or other specialized array libraries like NumPy.

## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [4]:
import array

list_ = [1, 2, 3, 4, 5]
array_list = array.array('i', [1, 2, 3, 4, 5])

# Print data types of elements in list_
print("Data types in list_:")
for item in list_:
    print(type(item))

# Print data types of elements in array_list
print("\nData types in array_list:")
for item in array_list:
    print(type(item))


Data types in list_:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types in array_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


## Q3. Considering the following changes in the variable, array_list:

Yes, there will be a difference in the data type of the elements between the `list_` variable and the `array_list` variable after performing the operation `array_list = np.array(object = list_, dtype = int)`. The elements in the `array_list` will be of the `int` data type, whereas the elements in the original `list_` variable will remain unchanged.

Let's print the data types of each element in both `list_` and `array_list`:

```python
import numpy as np

list_ = [1, 2, 3, 4, 5]
array_list = np.array(object=list_, dtype=int)

 Print data types of elements in list_
print("Data types in list_:")
for item in list_:
    print(type(item))

 Print data types of elements in array_list
print("\nData types in array_list:")
for item in array_list:
    print(type(item))


In the output, you can see that the elements in `array_list` have a data type of `numpy.int32`, which is a specific data type provided by NumPy, while the elements in the original `list_` variable remain integers. This is because we specified the `dtype=int` parameter when creating the NumPy array.

## Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Find the shape of num_array
shape = num_array.shape

# (ii) Find the size of num_array
size = num_array.size

print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.


In [6]:
import numpy as np

# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [9]:
import numpy as np
idendity_matrix = np.eye(5)
print(idendity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
